"""
Django settings for GSM project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')-t(o8a59lvea6#tsfucw%=weq=%sb@-xvppx8+e^jn8%5@rgz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CLIENT_SECRET_FILE = os.path.join(BASE_DIR, 'config/client_secret.json');
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sendgrid',
    'tweepy',
    'rest_framework',
    'reset_migrations',
    'gsm_utility'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GSM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GSM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
API_KEYS = {
    'sendgrid' : {
        'key' : "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"
    },
    'facebook' : {
        'secret' : '51894efd9105a21d60ea09deb3488438',
        'app_id' : '1633545903429163'
    },
    'twitter' : {
        'secret' : 'F1YKkRLBWqq0zIKjrYXsVaAgJ4QbB6x3rN4sV1UIbq3ksw34e2',
        'key'    : 'MOC32L0AJZ6zJcCeeSBA9Gtee'
    },
    'linkedin' : {
        'secret' : 'YqdNYzWhi4U5d95K',
        'app_id' : '81rs64ngv63h3b',
        'redirect_uri':"http://app.staging.globalsystemsmanagement.net/utility/auth/linkedin/callback/"
    },

}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': BASE_DIR+'/config/mysql.cnf',
        },
    },
    # 'utility': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'OPTIONS': {
    #         'read_default_file': BASE_DIR+'/config/mysql.cnf',
    #     },
    # }
}

WHITEDOMAINS_LIST = ["http://localhost:3000","http://localhost:9000","http://localhost:8000","http://db.staging.globalsystemsmanagement.net","https://web.staging.globalsystemsmanagement.net","http://localhost:63342","http://localhost:63343","http://app.staging.globalsystemsmanagement.net","http://staging.globalsystemsmanagement.net"]
WHITEHOSTS_LIST = ["staging.globalsystemsmanagement.net","db.staging.globalsystemsmanagement.net","localhost:8000","127.0.0.1:8000","web.staging.globalsystemsmanagement.net","app.staging.globalsystemsmanagement.net","localhost:3000"]

URLS = {
    'registration_verification':'http://staging.globalsystemsmanagement.net/auth/verify',
    'change_password':'http://staging.globalsystemsmanagement.net/auth/changepassword',
    # 'registration_verification':'http://staging.globalsystemsmanagement.net/auth/verify',
}

TOKEN_EXPIRY_TIMES = {
    'sessionToken': 12*60*60*1000,
    'anyOtherToken' : 7*24*60*60*1000
}
# DATABASE_ROUTERS = ['GSM.router.UtilityRouter']
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.dirname(BASE_DIR) + '/static/'
