# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSMUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(blank=True, max_length=255)),
                ('user_last_name', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('user_email_id', models.EmailField(default=None, max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('user_phone_number', models.CharField(default='+910000000000', max_length=15, validators=[django.core.validators.RegexValidator('(?:\\+?\\d{2})\\d{10}', "enter a valid number like '+918888888888'")])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'gsm_user',
                'managed': True,
            },
        ),
    ]
