# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_assets', models.CharField(choices=[('$0 - $20,000', b'a'), ('$20,000 - $40,000', b'b'), ('$40,000 - $80,000', b'c'), ('$80,000 - $120,000', b'd'), ('$120,000+', b'e')], default='a', max_length=1)),
                ('stock_trading_experience', models.CharField(choices=[('0 years', b'a'), ('1 years', b'b'), ('1-2 years', b'c'), ('2-5 years', b'd'), ('5 years+', b'e')], default='a', max_length=1)),
                ('bond_trading_experience', models.CharField(choices=[('0 years', b'a'), ('1 years', b'b'), ('1-2 years', b'c'), ('2-5 years', b'd'), ('5 years+', b'e')], default='a', max_length=1)),
                ('future_trading_experience', models.CharField(choices=[('0 years', b'a'), ('1 years', b'b'), ('1-2 years', b'c'), ('2-5 years', b'd'), ('5 years+', b'e')], default='a', max_length=1)),
                ('FX_trading_experience', models.CharField(choices=[('0 years', b'a'), ('1 years', b'b'), ('1-2 years', b'c'), ('2-5 years', b'd'), ('5 years+', b'e')], default='a', max_length=1)),
                ('feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsm_utility.GSMUsers')),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
    ]
