# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='gsm_user',
        ),
        migrations.RenameField(
            model_name='gsmusers',
            old_name='user_email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='gsmusers',
            old_name='user_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='gsmusers',
            old_name='user_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='gsmusers',
            old_name='user_phone_number',
            new_name='phone_number',
        ),
    ]
