# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0004_auto_20171223_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=255, unique=True)),
                ('password_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('valid_for', models.IntegerField()),
                ('valid', models.BooleanField(default=True)),
                ('gsm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsm_utility.GSMUsers')),
            ],
            options={
                'db_table': 'passwordtokens',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessiontoken',
            unique_together=set([('gsm_user', 'valid')]),
        ),
        migrations.AlterUniqueTogether(
            name='verificationtoken',
            unique_together=set([('gsm_user', 'valid')]),
        ),
        migrations.AlterUniqueTogether(
            name='passwordtoken',
            unique_together=set([('gsm_user', 'valid')]),
        ),
    ]
