# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0005_auto_20171224_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmusers',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
