# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0007_auto_20171225_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmusers',
            name='provider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
