# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0009_passwordtoken_mail_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterOauthToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oauth_token', models.CharField(max_length=255, unique=True)),
                ('oauth_token_secret', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'twitteroauthtokens',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='twitteroauthtoken',
            unique_together=set([('id', 'oauth_token')]),
        ),
    ]
