# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0010_auto_20171229_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkedinOauthState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'linkedinoauthstate',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='linkedinoauthstate',
            unique_together=set([('id', 'state')]),
        ),
    ]
