# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0011_auto_20171229_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmusers',
            name='deactivated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gsmusers',
            name='rd_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gsmusers',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
