# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0012_auto_20180109_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtrData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csiSym', models.CharField(max_length=4)),
                ('date', models.IntegerField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('openInterest', models.IntegerField()),
                ('contract', models.DecimalField(decimal_places=4, max_digits=10)),
                ('seasonality', models.DecimalField(decimal_places=4, max_digits=10)),
                ('atr20', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('usdAtr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('changePercent', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
