# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0013_atrdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrdata',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
