# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0016_auto_20180125_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrdata',
            name='atr20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='atrdata',
            name='changePercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='atrdata',
            name='usdAtr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
