# Generated by Django 2.0.1 on 2018-02-13 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_utility', '0018_auto_20180125_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalsdata',
            old_name='anti50',
            new_name='antiMlLastWorstFw',
        ),
        migrations.RenameField(
            model_name='signalsdata',
            old_name='antiHighEq',
            new_name='antiMlScalpAll',
        ),
        migrations.RenameField(
            model_name='signalsdata',
            old_name='antiPrev1',
            new_name='antiZz120',
        ),
        migrations.RenameField(
            model_name='signalsdata',
            old_name='highEq',
            new_name='mlLastBestFb',
        ),
        migrations.RenameField(
            model_name='signalsdata',
            old_name='lowEq',
            new_name='mlScalpBigFb',
        ),
        migrations.RenameField(
            model_name='signalsdata',
            old_name='prev1',
            new_name='mlSwingBigFb',
        ),
        migrations.RenameField(
            model_name='signalsdata',
            old_name='sea',
            new_name='prev10',
        ),
        migrations.AddField(
            model_name='signalsdata',
            name='zz30',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
